### ISSUE TITLE
Not reading from the config.json

### ISSUE THREAD

**Issue by brianmituka** [dthree/mailit#5]
I have already added my SMTP settings for gmail in the config.json by when I run `mailit --config config.json` I get the error `No host, port, user, pass specified in config` alternatively when I pass the data directly at run time I get the error:
`events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:465
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at Server._listen2 (net.js:1252:19)
    at listen (net.js:1301:10)
    at Server.listen (net.js:1392:7)
    at Function.listen (/home/mots/.nvm/versions/node/v7.8.0/lib/node_modules/mailit/node_modules/express/lib/application.js:618:24)
    at init (/home/mots/.nvm/versions/node/v7.8.0/lib/node_modules/mailit/index.js:27:7)
    at CommandInstance.<anonymous> (/home/mots/.nvm/versions/node/v7.8.0/lib/node_modules/mailit/index.js:48:3)
    at Session.session.execCommandSet (/home/mots/.nvm/versions/node/v7.8.0/lib/node_modules/mailit/node_modules/vorpal/dist/session.js:470:20)
    at Vorpal.vorpal._exec (/home/mots/.nvm/versions/node/v7.8.0/lib/node_modules/mailit/node_modules/vorpal/dist/vorpal.js:960:18)`
Here are my SMT settings in the config.json 

`{
    "host": "smtp.gmail.com",
    "port": 587,
    "secure": true,
    "user": "myemail@gmail.com",
    "pass": "pass",
    "rejectUnauthorized": false,
    "services": {
		"gmail.com": {
			"host": "smtp.gmail.com",
			"ports": [465, 587],
			"secure": [true, true]
		}
    }
}

`

**Comment by dthree** [comment]
Hey.

On the config, try passing the full path, such as `/usr/home/config.json`.

---

On the latter problem, check out this article on gmail:

https://community.nodemailer.com/using-gmail/

They're (specifically) pretty rigid on programmatic SMTP.
